services:
  app:
    build:
      context: .
      target: ${TARGET:-development}
    container_name: gin-app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=${GIN_MODE:-debug}
    restart: unless-stopped